name: Java CI Pipeline

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  update-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Increment patch version
        id: versioning
        run: |
          CURRENT_VERSION=$(grep "^version = " build.gradle.kts | cut -d'"' -f2)
          echo "Current Version: $CURRENT_VERSION"

          IFS='.' read -r major minor patch <<< "$CURRENT_VERSION"
          NEW_PATCH=$((patch + 1))
          NEW_VERSION="$major.$minor.$NEW_PATCH"
          echo "New Version: $NEW_VERSION"

          sed -i "s/^version = \".*\"/version = \"$NEW_VERSION\"/" build.gradle.kts
          
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Build docker image
        run: |
          docker build -t gradle-hello-world:${{ steps.versioning.outputs.new_version }} .

      - name: Generate SBOM
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: 'gradle-hello-world:${{ steps.versioning.outputs.new_version }}'
          format: 'cyclonedx'
          output: 'sbom.json'

      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-${{ steps.versioning.outputs.new_version }}
          path: sbom.json

      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/gradle-hello-world
          docker tag gradle-hello-world:${{ steps.versioning.outputs.new_version }} $IMAGE_NAME:${{ steps.versioning.outputs.new_version }}
          docker tag gradle-hello-world:${{ steps.versioning.outputs.new_version }} $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ steps.versioning.outputs.new_version }}
          docker push $IMAGE_NAME:latest

      - name: Install cosign
        uses: sigstore/cosign-installer@v4.0.0

      - name: Sign docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/gradle-hello-world
          cosign sign --yes $IMAGE_NAME:${{ steps.versioning.outputs.new_version }}

      - name: Pull and run
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/gradle-hello-world
          docker rmi -f $(docker images -q --filter=reference='*gradle-hello-world*')
          
          docker pull $IMAGE_NAME:${{ steps.versioning.outputs.new_version }}
          docker run --rm $IMAGE_NAME:${{ steps.versioning.outputs.new_version }}

      - name: Commit and push version update
        run: |
          git config --global user.name "github.actions"
          git config --global user.email "github.actions@github.com"
          git add build.gradle.kts
          git commit -m "increment version to ${{ steps.versioning.outputs.new_version }} [skip ci]"
          git push
